name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start containers
        run: make openresty-dev CONTAINER_ORCHESTRATOR_EXEC_OPTIONS="-T"

      - name: Run test-e2e-trace-context
        run: make openresty-unit-test CONTAINER_ORCHESTRATOR_EXEC_OPTIONS="-T"

      - name: Run openresty-test-e2e-trace-context
        run: make openresty-test-e2e-trace-context CONTAINER_ORCHESTRATOR_EXEC_OPTIONS="-T"

      - name: Run openresty-test-e2e
        run: make openresty-test-e2e CONTAINER_ORCHESTRATOR_EXEC_OPTIONS="-T"

      - name: Run api tests
        run: make api-test

